### PR TITLE
Add Intervals TenMinutes, ThirtyMinutes, Biweekly, Bimonthly & Quarter

### PR DESCRIPTION
**Pull request by JanBerktold**
Feedback on implementation would be appreciated.

### CODE REVIEW

**Comment by sent-hil** [comment]
Just skimmed through it, looks nice @JanBerktold. Btw, can you squash the commits into 1?

**Comment by sent-hil** [comment]
I ran test for `nearestInterval(time.Date(1981, time.July, 31, 01, 42, 0, 0, time.UTC), Bimonthly)`, it returns `'bimonthly:1981-07-16'`. This is an error, it should return 01 or 15 regardless of how many days are in month (28, 29, 31) etc.

**Comment by JanBerktold** [comment]
Squashed the commits.

Are you sure about splitting the month at the 15th? That might cause issues while trying to compare the first to the second half of a month.

**Comment by sent-hil** [comment]
Hmm, not sure tbh. Will merge for now. Btw, so far I've been the only one using the project, can you tell how you're using it?

**Pull request merged**
